### ISSUE TITLE
Cannot set property BlockStateInteger{} to 0 on Block{minecraft:water_cauldron

### ISSUE THREAD

**Issue by noiverre** [GamerMedic/UndeadPandemic#2]
```
[16:26:57 ERROR]: Could not pass event PlayerInteractEvent to UndeadPandemic v2.7.13-227
java.lang.IllegalArgumentException: Cannot set property BlockStateInteger{name=level, clazz=class java.lang.Integer, values=[1, 2, 3]} to 0 on Block{minecraft:water_cauldron}, it is not an allowed value
```

This happen when trying to purify water in cauldrons

**Comment by noiverre** [comment]
```
[16:13:49] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to UndeadPandemic v2.7.13-227
java.lang.IllegalArgumentException: Cannot set property BlockStateInteger{name=level, clazz=class java.lang.Integer, values=[1, 2, 3]} to 0 on Block{minecraft:water_cauldron}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.setValue(StateHolder.java:110) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.block.data.CraftBlockData.set(CraftBlockData.java:210) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at org.bukkit.craftbukkit.v1_20_R1.block.impl.CraftLayeredCauldron.setLevel(CraftLayeredCauldron.java:27) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at me.stevezr963.undeadpandemic.water.PurifyWater.onClickCauldron(PurifyWater.java:143) ~[UndeadPandemic-v2.7.13-227.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor770.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:git-Pufferfish-17]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:566) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1961) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by GamerMedic** [comment]
This issue has been resolved and will be corrected in the future versions.
