### ISSUE TITLE
 exception while executing task 140...

### ISSUE THREAD

**Issue by wpmidia** [GamerMedic/UndeadPandemic#3]
**I just put the plugin file in the "plugins" folder and started my server.**
...

[16:44:49 WARN]: [UndeadPandemic] Plugin UndeadPandemic v2.7.8-223 generated an exception while executing task 140
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because the return value of "me.stevezr963.undeadpandemic.utilities.ConfigManager.getMessage(me.stevezr963.undeadpandemic.utilities.ConfigMessage)" is null
        at me.stevezr963.undeadpandemic.UndeadPandemic$1.lambda$0(UndeadPandemic.java:153) ~[UndeadPandemic-v2.7.8-223.jar:?]
        at me.stevezr963.undeadpandemic.utilities.UpdateChecker.lambda$0(UpdateChecker.java:33) ~[UndeadPandemic-v2.7.8-223.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-171]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-171]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by GamerMedic** [comment]
Hi, sorry for the delay. I've only just spotted this.

Thanks for letting me know. I'll get it fixed.

**Comment by GamerMedic** [comment]
Issue has been resolved. A message in the language file was missing but has been added by default in newer versions.
