### ISSUE TITLE
Could not pass event PlayerInteractEvent to UndeadPandemic v2.7.13-227

### ISSUE THREAD

**Issue by GamerMedic** [GamerMedic/UndeadPandemic#6]
Submitted on behalf of Discord user MihDrix

I just saw this error in the console!

The error happens every time I fill a bottle with water from the cauldron. 
```
[11:18:29 ERROR]: Could not pass event PlayerInteractEvent to UndeadPandemic v2.7.13-227
java.lang.IllegalArgumentException: Cannot set property BlockStateInteger{name=level, clazz=class java.lang.Integer, values=[1, 2, 3]} to 0 on Block{minecraft:water_cauldron}, it is not an allowed value
        at net.minecraft.world.level.block.state.StateHolder.setValue(StateHolder.java:110) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.data.CraftBlockData.set(CraftBlockData.java:210) ~[paper-1.20.1.jar:git-Paper-171]
        at org.bukkit.craftbukkit.v1_20_R1.block.impl.CraftLayeredCauldron.setLevel(CraftLayeredCauldron.java:27) ~[paper-1.20.1.jar:git-Paper-171]
        at me.stevezr963.undeadpandemic.water.PurifyWater.onClickCauldron(PurifyWater.java:143) ~[UndeadPandemic-v2.7.13-227.jar:?]
```

**Comment by GamerMedic** [comment]
Resolved. Fix will be applied to v2.7.15.
